fragment IndustryEntity on Industry {
  title
  slug
  linkedFrom {
    industryGroupCollection {
      items {
        title
        slug
      }
    }
  }
}
query GetIndustries {
  industryCollection {
    items {
      ...IndustryEntity
    }
  }
}
