fragment LinkedAnswerEntity on LinkedAnswer {
  title
  isEnd
  slug
  id
  sys {
    id
  }
  nextQuestion {
    title
    sys {
      id
    }
  }
}

fragment LinkedQuestionEntity on LinkedQuestion {
  title
  isStart
  slug
  answersCollection(limit: 10) {
    items {
      ...LinkedAnswerEntity
    }
  }
  sys {
    id
  }
}

query GetLinkedQuestions {
  linkedQuestionCollection {
    items {
      ...LinkedQuestionEntity
    }
  }
}
