fragment QuestionEntity on Question {
  title
  answers
  type
  slug
  want
  sys {
    id
  }
}
query GetQuestions {
  questionCollection {
    items {
      ...QuestionEntity
    }
  }
}

fragment JobEntity on Jobs {
  title
  logic
  move
  music
  space
  inner
  communication
  word
  linkedFrom {
    industryCollection(limit: 10) {
      items {
        title
        slug
      }
    }
  }
}
query GetJobs {
  jobsCollection {
    items {
      ...JobEntity
    }
  }
}
